version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
      - "15674:15674"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    stop_grace_period: 30s

  consumer:
    build: ./consumer
    ports:
      - "4000:4000"  # Macht die Status-API des Consumers von außen erreichbar
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy

  # producer:
  #   build: ./producer
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - RABBITMQ_URL=amqp://rabbitmq:5672
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management, rabbitmq_web_stomp]." 

networks:
  app-network:
    driver: bridge

volumes:
  rabbitmq_data:
