version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  producer:
    build:
      context: ./
      dockerfile: backend/producer/Dockerfile
    environment:
      RABBIT_URL: "amqp://rabbitmq"
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  consumer:
    build:
      context: ./
      dockerfile: backend/consumer/Dockerfile
    environment:
      RABBIT_URL: "amqp://rabbitmq"
      TAPO_EMAIL: "ibrtkc@yahoo.com"
      TAPO_PASSWORD: "dypzeG-myxpez-1wukqe"
      TAPO_DEVICE_ID: 8023C48528797B47756D91E839E4C966237FB3C7
      TAPO_DEVICE_IP: "192.168.216.238"
      DEV_MODE: "false"
    depends_on:
      - rabbitmq

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - producer
      - consumer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5
